package view;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;

import controller.MainEditorController;
import java.awt.Color;
import java.awt.dnd.DropTarget;
import java.util.logging.Logger;
import model.MainEditorModel;
import model.trace.TracePoint;
import model.trace.TraceCommand;
import model.trace.PriorityClass;
import utils.DropListener;
import view.handler.VisualComponentHandler;
import view.handler.CustomListModelHandler;
import utils.TcmParser;
import utils.events.EventBaseClass;
import utils.events.EventDisableAllComponentControls;
import utils.events.EventEnableAllComponentControls;
import utils.events.EventUpdateAllLists;
import utils.events.EventUpdateCurrentComponentNameLabel;
import utils.events.EventUpdatePriorityClassList;
import utils.events.EventUpdateCurrentTcmPath;
import utils.events.EventUpdateTcmPathForegroundToNormal;
import utils.events.EventUpdateTcmPathForegroundToRed;
import utils.events.EventUpdateTraceCommandList;
import utils.events.EventUpdateTracePointList;
import utils.misc;

/**
 *
 * @author uidj5418
 */
public class MainEditorFrame extends javax.swing.JFrame {
    
    // MVC variables
    private MainEditorController    controller;
    private MainEditorModel         model;
    
    // Graphic swing component handlers
    private VisualComponentHandler  componentHandler;
    
    // Drag and Drop objects
    private DropTarget              dropTargetObj;
    private DropListener            dropListenerObj;
    
    public  boolean  fileIsAlreadyLoaded =      false;
    public  String   currentFileLoaded =        "";
    public  String   currentComponentName =     "";
    
    /**
     * Creates new form NewJFrame
     */
    public MainEditorFrame(MainEditorController controller, MainEditorModel model) {
        
        this.controller = controller;
        this.model = model;
        //
        this.controller.setModelRef(model);
        
        this.componentHandler =             new VisualComponentHandler();
        
        this.lookAndFeelSetup();
        this.initComponents();
        this.initDragAndDrop();
    }

    public void initDragAndDrop(){
        this.dropListenerObj = new DropListener();
        this.dropTargetObj = new DropTarget(this, this.dropListenerObj);
        this.controller.setDropListenerObject(dropListenerObj);
    }
    
    public DropListener getDropListenerObject(){
        return this.dropListenerObj;
    }
    
    /**
     * Configure "Look And Feel Like Settings"
     */
    public void lookAndFeelSetup() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainEditorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainEditorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainEditorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainEditorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        fileChooser = new javax.swing.JFileChooser();
        popupMenuTcmPath = new javax.swing.JPopupMenu();
        menuOptionCopyTcmPath = new javax.swing.JMenuItem();
        panelMenu = new javax.swing.JPanel();
        jLabelComponent = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelComponentName = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonSaveTcm = new javax.swing.JButton();
        panelOpenTcm = new javax.swing.JPanel();
        jButtonOpenTcm = new javax.swing.JButton();
        jTextFieldTcmPath = new javax.swing.JTextField();
        separatorTcmFile = new javax.swing.JSeparator();
        jButtonNewTcm = new javax.swing.JButton();
        panelTracePoints = new javax.swing.JPanel();
        jLabelTracepoints = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListTracePoints = new javax.swing.JList();
        panelTracePointsButtons = new javax.swing.JPanel();
        jButtonAddTracePoint = new javax.swing.JButton();
        jButtonEditTracePoint = new javax.swing.JButton();
        jButtonRemoveTracePoint = new javax.swing.JButton();
        separatorTpTc = new javax.swing.JSeparator();
        PanelTraceCommands = new javax.swing.JPanel();
        jLabelTraceCommands = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListTraceCommands = new javax.swing.JList();
        panelTraceCommandsButtons = new javax.swing.JPanel();
        jButtonRemoveTraceCommand = new javax.swing.JButton();
        jButtonEditTraceCommand = new javax.swing.JButton();
        jButtonAddTraceCommand = new javax.swing.JButton();
        separatorTcPc = new javax.swing.JSeparator();
        panelPriorityClasses = new javax.swing.JPanel();
        jLabelPriorityClasses = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListPriorityClasses = new javax.swing.JList();
        panelPriorityClassesButtons = new javax.swing.JPanel();
        jButtonAddPriorityClass = new javax.swing.JButton();
        jButtonEditPriorityClass = new javax.swing.JButton();
        jButtonRemovePriorityClass = new javax.swing.JButton();
        separatorBottom = new javax.swing.JSeparator();
        menuBarTcmEditor = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        menuOptionCopyTcmPath.setText("Copy TCM absolute path");
        menuOptionCopyTcmPath.setToolTipText("");
        menuOptionCopyTcmPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOptionCopyTcmPathActionPerformed(evt);
            }
        });
        popupMenuTcmPath.add(menuOptionCopyTcmPath);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trace TCM Editor");
        setResizable(false);

        jLabelComponent.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelComponent.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelComponent.setText("Component :");
        jLabelComponent.setEnabled(false);

        jLabelComponentName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelComponentName.setText(" ");
        jLabelComponentName.setToolTipText("Current Component Name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
        );

        jButtonSaveTcm.setBackground(new java.awt.Color(0, 153, 0));
        jButtonSaveTcm.setText("Save TCM File...");
        jButtonSaveTcm.setEnabled(false);
        jButtonSaveTcm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveTcmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSaveTcm, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(jButtonSaveTcm, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                        .addComponent(jLabelComponent, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelComponentName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator2))
                .addContainerGap())
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelComponent, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelComponentName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButtonOpenTcm.setText("Open TCM File...");
        jButtonOpenTcm.setToolTipText("Opens the file explorer to choose a TCM file from your system");
        jButtonOpenTcm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpenTcmActionPerformed(evt);
            }
        });

        jTextFieldTcmPath.setEditable(false);
        jTextFieldTcmPath.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldTcmPath.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldTcmPath.setToolTipText("Absolute path to the TCM file loaded (right click for copy options)");
        jTextFieldTcmPath.setDropMode(javax.swing.DropMode.INSERT);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, popupMenuTcmPath, org.jdesktop.beansbinding.ObjectProperty.create(), jTextFieldTcmPath, org.jdesktop.beansbinding.BeanProperty.create("componentPopupMenu"));
        bindingGroup.addBinding(binding);

        jButtonNewTcm.setBackground(new java.awt.Color(51, 102, 255));
        jButtonNewTcm.setText("New");
        jButtonNewTcm.setToolTipText("Creates a new TCM file from the scratch");
        jButtonNewTcm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewTcmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOpenTcmLayout = new javax.swing.GroupLayout(panelOpenTcm);
        panelOpenTcm.setLayout(panelOpenTcmLayout);
        panelOpenTcmLayout.setHorizontalGroup(
            panelOpenTcmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpenTcmLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOpenTcmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separatorTcmFile, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
                    .addGroup(panelOpenTcmLayout.createSequentialGroup()
                        .addComponent(jButtonNewTcm, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonOpenTcm, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldTcmPath, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        panelOpenTcmLayout.setVerticalGroup(
            panelOpenTcmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpenTcmLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOpenTcmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOpenTcm, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTcmPath, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNewTcm, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(separatorTcmFile, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        jLabelTracepoints.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTracepoints.setText("Trace Points");
        jLabelTracepoints.setEnabled(false);

        jListTracePoints.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListTracePoints.setEnabled(false);
        jScrollPane2.setViewportView(jListTracePoints);

        javax.swing.GroupLayout panelTracePointsLayout = new javax.swing.GroupLayout(panelTracePoints);
        panelTracePoints.setLayout(panelTracePointsLayout);
        panelTracePointsLayout.setHorizontalGroup(
            panelTracePointsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTracePointsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTracePointsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelTracepoints, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        panelTracePointsLayout.setVerticalGroup(
            panelTracePointsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTracePointsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTracepoints)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonAddTracePoint.setText("Add");
        jButtonAddTracePoint.setToolTipText("Adds a new Trace Point");
        jButtonAddTracePoint.setEnabled(false);
        jButtonAddTracePoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddTracePointActionPerformed(evt);
            }
        });

        jButtonEditTracePoint.setText("Edit");
        jButtonEditTracePoint.setEnabled(false);

        jButtonRemoveTracePoint.setBackground(java.awt.Color.red);
        jButtonRemoveTracePoint.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonRemoveTracePoint.setText("Remove");
        jButtonRemoveTracePoint.setToolTipText("Removes the selected Trace Point from the list");
        jButtonRemoveTracePoint.setEnabled(false);
        jButtonRemoveTracePoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveTracePointActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTracePointsButtonsLayout = new javax.swing.GroupLayout(panelTracePointsButtons);
        panelTracePointsButtons.setLayout(panelTracePointsButtonsLayout);
        panelTracePointsButtonsLayout.setHorizontalGroup(
            panelTracePointsButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTracePointsButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTracePointsButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAddTracePoint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEditTracePoint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRemoveTracePoint, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelTracePointsButtonsLayout.setVerticalGroup(
            panelTracePointsButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTracePointsButtonsLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jButtonAddTracePoint, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonEditTracePoint, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRemoveTracePoint, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PanelTraceCommands.setPreferredSize(new java.awt.Dimension(387, 194));

        jLabelTraceCommands.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelTraceCommands.setText("Trace Commands");
        jLabelTraceCommands.setEnabled(false);

        jListTraceCommands.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListTraceCommands.setEnabled(false);
        jScrollPane1.setViewportView(jListTraceCommands);

        javax.swing.GroupLayout PanelTraceCommandsLayout = new javax.swing.GroupLayout(PanelTraceCommands);
        PanelTraceCommands.setLayout(PanelTraceCommandsLayout);
        PanelTraceCommandsLayout.setHorizontalGroup(
            PanelTraceCommandsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTraceCommandsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelTraceCommandsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTraceCommands, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        PanelTraceCommandsLayout.setVerticalGroup(
            PanelTraceCommandsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTraceCommandsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTraceCommands)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonRemoveTraceCommand.setBackground(java.awt.Color.red);
        jButtonRemoveTraceCommand.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonRemoveTraceCommand.setText("Remove");
        jButtonRemoveTraceCommand.setToolTipText("Removes the selected Trace Command from the list");
        jButtonRemoveTraceCommand.setEnabled(false);
        jButtonRemoveTraceCommand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveTraceCommandActionPerformed(evt);
            }
        });

        jButtonEditTraceCommand.setText("Edit");
        jButtonEditTraceCommand.setEnabled(false);

        jButtonAddTraceCommand.setText("Add");
        jButtonAddTraceCommand.setToolTipText("Adds a new Trace Command");
        jButtonAddTraceCommand.setEnabled(false);
        jButtonAddTraceCommand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddTraceCommandActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTraceCommandsButtonsLayout = new javax.swing.GroupLayout(panelTraceCommandsButtons);
        panelTraceCommandsButtons.setLayout(panelTraceCommandsButtonsLayout);
        panelTraceCommandsButtonsLayout.setHorizontalGroup(
            panelTraceCommandsButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTraceCommandsButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTraceCommandsButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRemoveTraceCommand, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(jButtonEditTraceCommand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAddTraceCommand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelTraceCommandsButtonsLayout.setVerticalGroup(
            panelTraceCommandsButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTraceCommandsButtonsLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jButtonAddTraceCommand, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonEditTraceCommand, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRemoveTraceCommand, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabelPriorityClasses.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelPriorityClasses.setText("Priority Classes");
        jLabelPriorityClasses.setEnabled(false);

        jListPriorityClasses.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListPriorityClasses.setEnabled(false);
        jScrollPane3.setViewportView(jListPriorityClasses);

        javax.swing.GroupLayout panelPriorityClassesLayout = new javax.swing.GroupLayout(panelPriorityClasses);
        panelPriorityClasses.setLayout(panelPriorityClassesLayout);
        panelPriorityClassesLayout.setHorizontalGroup(
            panelPriorityClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPriorityClassesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPriorityClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPriorityClasses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        panelPriorityClassesLayout.setVerticalGroup(
            panelPriorityClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPriorityClassesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPriorityClasses)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonAddPriorityClass.setText("Add");
        jButtonAddPriorityClass.setEnabled(false);
        jButtonAddPriorityClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddPriorityClassActionPerformed(evt);
            }
        });

        jButtonEditPriorityClass.setText("Edit");
        jButtonEditPriorityClass.setEnabled(false);

        jButtonRemovePriorityClass.setBackground(java.awt.Color.red);
        jButtonRemovePriorityClass.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonRemovePriorityClass.setText("Remove");
        jButtonRemovePriorityClass.setEnabled(false);
        jButtonRemovePriorityClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemovePriorityClassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPriorityClassesButtonsLayout = new javax.swing.GroupLayout(panelPriorityClassesButtons);
        panelPriorityClassesButtons.setLayout(panelPriorityClassesButtonsLayout);
        panelPriorityClassesButtonsLayout.setHorizontalGroup(
            panelPriorityClassesButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPriorityClassesButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPriorityClassesButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAddPriorityClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEditPriorityClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRemovePriorityClass, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelPriorityClassesButtonsLayout.setVerticalGroup(
            panelPriorityClassesButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPriorityClassesButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAddPriorityClass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonEditPriorityClass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRemovePriorityClass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jMenu3.setText("jMenu3");
        jMenu1.add(jMenu3);

        menuBarTcmEditor.add(jMenu1);

        jMenu2.setText("Edit");
        menuBarTcmEditor.add(jMenu2);

        jMenu4.setText("About");
        menuBarTcmEditor.add(jMenu4);

        setJMenuBar(menuBarTcmEditor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(separatorBottom)
                    .addComponent(panelOpenTcm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panelTracePoints, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelTracePointsButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(separatorTpTc, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PanelTraceCommands, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelTraceCommandsButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(separatorTcPc)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panelPriorityClasses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelPriorityClassesButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelOpenTcm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelTracePointsButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelTracePoints, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(separatorTpTc, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PanelTraceCommands, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(panelTraceCommandsButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(separatorTcPc, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelPriorityClassesButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelPriorityClasses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separatorBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelPriorityClassesButtons.getAccessibleContext().setAccessibleName("");

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOpenTcmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpenTcmActionPerformed
        boolean userOption = true;
        if(this.fileIsAlreadyLoaded){
            userOption = this.componentHandler.showAcceptCancelDialog(
                this,
                "TCM file '...' is already loaded, are you sure you want to continue?");
        }
        if(userOption == true){
            String fileName = this.componentHandler.chooseTcmFileFromWindowsExplorer(this);
            if(!(fileName == null)){
                this.componentHandler.setTextInTextFieldComponent(this.jTextFieldTcmPath, fileName);
                this.currentFileLoaded = fileName;
                this.fileIsAlreadyLoaded = true;
                //Parse file
                this.controller.openTcmFile(fileName);
                this.update( new EventEnableAllComponentControls() );
            }
        }
    }//GEN-LAST:event_jButtonOpenTcmActionPerformed

    private void jButtonAddTracePointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddTracePointActionPerformed
        this.controller.openTracePointWindow();
    }//GEN-LAST:event_jButtonAddTracePointActionPerformed

    private void jButtonRemoveTracePointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveTracePointActionPerformed
        String itemSelected = this.jListTracePoints.getSelectedValue().toString();
        Logger.getGlobal().info(
            String.format("[View] Selected Item to be removed: \"%s\"", itemSelected));
        this.controller.deleteTracePointData(itemSelected);
    }//GEN-LAST:event_jButtonRemoveTracePointActionPerformed

    private void menuOptionCopyTcmPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOptionCopyTcmPathActionPerformed
        this.componentHandler.copyTextFieldComponentContentToClipboard(this.jTextFieldTcmPath);
    }//GEN-LAST:event_menuOptionCopyTcmPathActionPerformed

    private void jButtonAddTraceCommandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddTraceCommandActionPerformed
        this.controller.openTraceCommandWindow();
    }//GEN-LAST:event_jButtonAddTraceCommandActionPerformed

    private void jButtonRemoveTraceCommandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveTraceCommandActionPerformed
        String itemSelected = this.jListTraceCommands.getSelectedValue().toString();
        Logger.getGlobal().info(
            String.format("[View] Selected Item to be removed: \"%s\"", itemSelected));
        this.controller.deleteTraceCommandData(itemSelected);
    }//GEN-LAST:event_jButtonRemoveTraceCommandActionPerformed

    private void jButtonAddPriorityClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPriorityClassActionPerformed
        this.controller.openPriorityClassWindow();
    }//GEN-LAST:event_jButtonAddPriorityClassActionPerformed

    private void jButtonRemovePriorityClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemovePriorityClassActionPerformed
        String itemSelected = this.jListPriorityClasses.getSelectedValue().toString();
        Logger.getGlobal().info(
            String.format("[View] Selected Item to be removed: \"%s\"", itemSelected));
        this.controller.deletePriorityClassData(itemSelected);
    }//GEN-LAST:event_jButtonRemovePriorityClassActionPerformed

    private void jButtonSaveTcmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveTcmActionPerformed
        String tcmFileName = this.controller.chooseFileDestination(this.currentComponentName);
        if (tcmFileName != null){
            this.controller.createTcmFile(tcmFileName, this.currentComponentName);
            this.update( new EventUpdateCurrentComponentNameLabel() );
            this.update( new EventUpdateCurrentTcmPath());
        }
    }//GEN-LAST:event_jButtonSaveTcmActionPerformed

    private void jButtonNewTcmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewTcmActionPerformed
        String componentName = this.controller.createNewComponentName();
        if (componentName != null && !componentName.isEmpty()){
            this.currentComponentName = componentName;
            this.update( new EventEnableAllComponentControls() );
            this.update( new EventUpdateCurrentComponentNameLabel() );
        }
    }//GEN-LAST:event_jButtonNewTcmActionPerformed
    
    public void setCurrentComponentName(String componentName){
        this.currentComponentName = componentName;
    }
    
    public void setCurrentFileLoaded(String absoluteFilePath){
        this.currentFileLoaded = absoluteFilePath;
    }
    
    public void update(EventBaseClass evt){
        if ( evt instanceof EventUpdateTracePointList ){
            Logger.getGlobal().info(
                String.format("[View] Event update: \"%s\"", evt.getClass().getSimpleName()));
            this.jListTracePoints.setModel(
                this.controller.getTracePointList()
            );
        }
        else if ( evt instanceof EventUpdateTraceCommandList ){
            Logger.getGlobal().info(
                String.format("[View] Event update: \"%s\"", evt.getClass().getSimpleName()));
            this.jListTraceCommands.setModel(
                this.controller.getTraceCommandList()
            );
        }
        else if ( evt instanceof EventUpdatePriorityClassList ){
            Logger.getGlobal().info(
                String.format("[View] Event update: \"%s\"", evt.getClass().getSimpleName()));
            this.jListPriorityClasses.setModel(
                this.controller.getPriorityClassList()
            );
        }
        else if ( evt instanceof EventUpdateAllLists ){
            Logger.getGlobal().info(
                String.format("[View] Event update: \"%s\"", evt.getClass().getSimpleName()));
            this.update( new EventUpdateTracePointList() );
            this.update( new EventUpdateTraceCommandList() );
            this.update( new EventUpdatePriorityClassList() );
        }
        else if ( evt instanceof EventUpdateCurrentComponentNameLabel ){
            Logger.getGlobal().info(
                String.format("[View] Event update: \"%s\"", evt.getClass().getSimpleName()));
            this.jLabelComponentName.setText(this.currentComponentName);
        }
        else if ( evt instanceof EventUpdateCurrentTcmPath ){
            Logger.getGlobal().info(
                String.format("[View] Event update: \"%s\"", evt.getClass().getSimpleName()));
            this.jTextFieldTcmPath.setText(this.currentFileLoaded);
            this.fileIsAlreadyLoaded = true;
        }
        else if ( evt instanceof EventUpdateTcmPathForegroundToRed ){
            Logger.getGlobal().info(
                String.format("[View] Event update: \"%s\"", evt.getClass().getSimpleName()));
            this.jTextFieldTcmPath.setForeground(Color.RED);
        }
        else if ( evt instanceof EventUpdateTcmPathForegroundToNormal ){
            Logger.getGlobal().info(
                String.format("[View] Event update: \"%s\"", evt.getClass().getSimpleName()));
            this.jTextFieldTcmPath.setForeground(Color.DARK_GRAY);
        }
        else if ( evt instanceof EventDisableAllComponentControls ){
            Logger.getGlobal().info(
                String.format("[View] Event update: \"%s\"", evt.getClass().getSimpleName()));
            this.jButtonAddTracePoint.setEnabled(false);
            this.jButtonAddTraceCommand.setEnabled(false);
            this.jButtonAddPriorityClass.setEnabled(false);
            this.jButtonEditTracePoint.setEnabled(false);
            this.jButtonEditTraceCommand.setEnabled(false);
            this.jButtonEditPriorityClass.setEnabled(false);
            this.jButtonRemoveTracePoint.setEnabled(false);
            this.jButtonRemoveTraceCommand.setEnabled(false);
            this.jButtonRemovePriorityClass.setEnabled(false);
            this.jButtonSaveTcm.setEnabled(false);
            
            this.jListTracePoints.setEnabled(false);
            this.jListTraceCommands.setEnabled(false);
            this.jListPriorityClasses.setEnabled(false);
            
            this.jLabelTracepoints.setEnabled(false);
            this.jLabelTraceCommands.setEnabled(false);
            this.jLabelPriorityClasses.setEnabled(false);
            this.jLabelComponent.setEnabled(false);
        }
        else if ( evt instanceof EventEnableAllComponentControls ){
            Logger.getGlobal().info(
                String.format("[View] Event update: \"%s\"", evt.getClass().getSimpleName()));
            this.jButtonAddTracePoint.setEnabled(true);
            this.jButtonAddTraceCommand.setEnabled(true);
            this.jButtonAddPriorityClass.setEnabled(true);
            this.jButtonEditTracePoint.setEnabled(true);
            this.jButtonEditTraceCommand.setEnabled(true);
            this.jButtonEditPriorityClass.setEnabled(true);
            this.jButtonRemoveTracePoint.setEnabled(true);
            this.jButtonRemoveTraceCommand.setEnabled(true);
            this.jButtonRemovePriorityClass.setEnabled(true);
            this.jButtonSaveTcm.setEnabled(true);
            
            this.jListTracePoints.setEnabled(true);
            this.jListTraceCommands.setEnabled(true);
            this.jListPriorityClasses.setEnabled(true);
            
            this.jLabelTracepoints.setEnabled(true);
            this.jLabelTraceCommands.setEnabled(true);
            this.jLabelPriorityClasses.setEnabled(true);
            this.jLabelComponent.setEnabled(true);
        }
    }

    //<editor-fold defaultstate="collapsed" desc=" Run Method: Code not longer needed, but keep it ">
    public static void run() {
        /* Set the Nimbus look and feel */
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainEditorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainEditorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainEditorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainEditorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainEditorFrame(null, null).setVisible(true);
            }
        });
    }
    //</editor-fold>
    //</editor-fold>
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelTraceCommands;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JButton jButtonAddPriorityClass;
    private javax.swing.JButton jButtonAddTraceCommand;
    private javax.swing.JButton jButtonAddTracePoint;
    private javax.swing.JButton jButtonEditPriorityClass;
    private javax.swing.JButton jButtonEditTraceCommand;
    private javax.swing.JButton jButtonEditTracePoint;
    private javax.swing.JButton jButtonNewTcm;
    private javax.swing.JButton jButtonOpenTcm;
    private javax.swing.JButton jButtonRemovePriorityClass;
    private javax.swing.JButton jButtonRemoveTraceCommand;
    private javax.swing.JButton jButtonRemoveTracePoint;
    private javax.swing.JButton jButtonSaveTcm;
    private javax.swing.JLabel jLabelComponent;
    private javax.swing.JLabel jLabelComponentName;
    private javax.swing.JLabel jLabelPriorityClasses;
    private javax.swing.JLabel jLabelTraceCommands;
    private javax.swing.JLabel jLabelTracepoints;
    private javax.swing.JList jListPriorityClasses;
    private javax.swing.JList jListTraceCommands;
    private javax.swing.JList jListTracePoints;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldTcmPath;
    private javax.swing.JMenuBar menuBarTcmEditor;
    private javax.swing.JMenuItem menuOptionCopyTcmPath;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelOpenTcm;
    private javax.swing.JPanel panelPriorityClasses;
    private javax.swing.JPanel panelPriorityClassesButtons;
    private javax.swing.JPanel panelTraceCommandsButtons;
    private javax.swing.JPanel panelTracePoints;
    private javax.swing.JPanel panelTracePointsButtons;
    private javax.swing.JPopupMenu popupMenuTcmPath;
    private javax.swing.JSeparator separatorBottom;
    private javax.swing.JSeparator separatorTcPc;
    private javax.swing.JSeparator separatorTcmFile;
    private javax.swing.JSeparator separatorTpTc;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
